### ISSUE TITLE
数値にマイナスを入れると二乗以外正しく計算されない

### ISSUE THREAD

**Issue by kake-p** [TaikiIkemoto/git-training-2024#6]
## 操作手順
* 数値にマイナスを入れる

## 本来の想定
* 〜したら
* 〜になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by mikadonec** [comment]
左側のマスにマイナスを入れたとき正常に動きません
